First Push of HMOS Lib Code
applibgroup/AnchorSheetBehavior pull request #1
Opened 2021-06-29 10:39 UTC by Sanku-Yogesh

HMOS Codes + Original Android Readme

2021-06-29 15:55 UTC, kanaksony requested changes
Proper indentation, extra and necessary spacing in many files missing, and code reformating required.

2021-06-29 15:55 UTC, kanaksony commented on anchorsheetlayout/src/main/java/com/hardsoftstudio/anchorsheetlayout/AnchorSheetLayout.java
> +    private void initDragHelper(){
Many functions are missing documentation.

2021-07-01 06:19 UTC, Sanku-Yogesh commented on anchorsheetlayout/src/main/java/com/hardsoftstudio/anchorsheetlayout/AnchorSheetLayout.java
> +    private void initDragHelper(){
added documentation

2021-07-07 04:59 UTC, kanaksony approved these changes

2021-07-07 05:12 UTC, closed without merging